#! /bin/bash

#path to wallpaper folder
bg_folder_path="/home/hodes/wallpapers/bg_images"
current_bg="/home/hodes/wallpapers/current.txt"

init(){
    #path of image    
    bg_image_path="$bg_folder_path/arch01.png"
    #create temporary file and write the path of the current wallpaper in it
    touch "$current_bg"
    echo "$bg_image_path" > "$current_bg"

    #set bg and activate pywal on it
    hyprctl hyprpaper unload all   
    hyprctl hyprpaper preload $(cat $current_bg)
    hyprctl hyprpaper wallpaper "eDP-1, $(cat $current_bg)"
    wal -i "$(cat $current_bg)"
}

change_bg(){
 echo "hi"
}

check_file(){
# Check if the correct number of arguments is provided
if [ $# -ne 2 ]; then
  echo "Usage: $0 <folder_path> <n>"
  exit 1
fi

folder_path=$1
n=$2

# Get the nth file in the folder
file=$(ls -1 "$folder_path" | sed -n "${n}p")

# Check if the file exists
if [ -z "$file" ]; then
  echo "No such file"
  exit 1
fi

echo "Nth file: $file"
}

[[ "$1" == "init" ]] && init && exit
[[ "1" == "ckeck_file" ]] && check_files && exit
