#!/bin/bash
# Opens eww calendar

LOCK_FILE="$HOME/.cache/eww-calendar.lock"
#EWW_BIN="~/eww/target/release/eww"

run() {
    ~/eww/target/release/eww open top
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    ~/eww/target/release/eww daemon
    sleep 1
fi

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    ~/eww/target/release/eww close top
    rm "$LOCK_FILE"
fi
