#!/bin/bash
convert(){
  local value=$1
  input_text=$(amixer get "$value")

  result=$(echo "$input_text" | grep -o '\[[[:alpha:]]*\]' | tr -d '[]' | awk 'BEGIN{ORS=" "}{print}')
  # Set IFS (Internal Field Separator) to space
  IFS=' '
 
  # Read the input text into an array of characters
  read -a char_array <<< "$result"

  if [[ "$result" == *"on"* ]]; then
    echo true
  else
    echo false
  fi

  # Print the array elements
  #echo "Result: ${char_array[@]}"
}

[ "$1" = "master" ] && convert "Master" && exit
[ "$1" = "capture" ] && convert "Capture" && exit
exit
