#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"
status="$(cat "$bat/status")"
icon() {

if [ "$status" != "Charging" ]; then
    a=""
else
    a=""
fi

if [ "$per" -gt "99" ]; then
	icon="$a  󰁹"
elif [ "$per" -gt "90" ]; then
	icon="$a 󰂂"
elif [ "$per" -gt "80" ]; then
	icon="$a 󰂁"
elif [ "$per" -gt "70" ]; then
	icon="$a 󰂀"
elif [ "$per" -gt "60" ]; then
	icon="$a 󰁿"
elif [ "$per" -gt "50" ]; then
	icon="$a 󰁾"
elif [ "$per" -gt "40" ]; then
	icon="$a 󰁽"
elif [ "$per" -gt "30" ]; then
	icon="$a 󰁼"
elif [ "$per" -gt "20" ]; then
	icon="$a 󰁻"
elif [ "$per" -gt "10" ]; then
	icon="$a 󰁺"
elif [ "$per" -gt "1" ]; then
	icon="$a 󱃍"
	notify-send -u critical "Battery Low" "Connect Charger"
else
        echo "" && exit
fi
echo "$icon"
}

percent() {
echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
exit
